rails_example_app/tdd/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # For list of routes currently supported by the APP
  # either
  #   point browser to: localhost:3000/rails/info/routes
  # or run
  #   rails routes  # in the rails app' project root
  # root "players#index"
  root "users#index"

  resources :players
  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]

  get "log_out" => "sessions#destroy"
  # get "players" => "players#index"
  # get "players/new" => "players#new"
  # post "players" => "players#create"
  # get "players/:id" => "players#show", as: "player"
  # get "players/:id/edit" => "players#edit", as: "player_edit"
  # patch "players/:id" => "players#update"
  # delete "players/:id" => "players#destroy"
end

rails_example_app/tdd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_example_app/tdd/app/models/player.rb
class Player < ApplicationRecord
  validates :first_name, :last_name, presence: true
end

rails_example_app/tdd/app/models/user.rb
class User < ApplicationRecord
  has_secure_password  # Was generated by rails via: rails g model user name:string email:string password:digest

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

rails_example_app/tdd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless session[:user_id]
      flash[:errors] = ["You must login first"]
      redirect_to root_path
    end
  end
end

rails_example_app/tdd/app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :require_login # Before action will be executed ensure that user is logged in

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    # fail   # can be used to double check the form params being passed into by the incoming request

    # player = Player.new
    # player.first_name = params[:player][:first_name]
    # player.last_name = params[:player][:last_name]
    player = Player.new(player_params)

    if player.save
      # redirect_to "/players"
      redirect_to players_path
    else
      flash[:errors] = player.errors.full_messages
      # redirect_to "/players/new" #the route where we came from, the so called 'back' route
      redirect_back fallback_location: "/players/new"
      # redirect_to :back #the route where we came from, the so called 'back' route
    end
  end

  def show
    # fail
    @player = Player.find(params[:id])
  end

  def edit
    # fail
    @player = Player.find(params[:id])
  end

  def update
    player = Player.find(params[:id])
    if player.update(player_params)
      # redirect_to "/players"
      # redirect_to :root
      redirect_to players_path
    else
      flash[:errors] = player.errors.full_messages
      # redirect_to "/players/#{player.id}/edit"
      # redirect_to :back #the route where we came from, the so called 'back' route
      redirect_back fallback_location: players_path
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    # redirect_to "/players"
    redirect_to players_path
  end

  private
  def player_params
    params.require(:player).permit(:first_name, :last_name) # Only expect those params being passed in from the incoming POST request
  end

end

rails_example_app/tdd/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # fail
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to players_path
    else
      flash[:errors] = ["Invalid Combination"]
      # redirect_to :back
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end
end

rails_example_app/tdd/app/controllers/users_controller.rb
# Controlling 1 page for registration and login
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to players_path
    else
      flash[:errors] = user.errors.full_messages
      # redirect_to :back
      redirect_back fallback_location: root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

rails_example_app/tdd/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_example_app/tdd/app/helpers/players_helper.rb
module PlayersHelper
end

rails_example_app/tdd/app/helpers/users_helper.rb
module UsersHelper
end

rails_example_app/tdd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tdd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

rails_example_app/tdd/app/views/players/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for(@player) do |f| %>
  <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
  </p>
  <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
  </p>
  <%= f.submit %>
<% end %>

rails_example_app/tdd/app/views/players/edit.html.erb
<% content_for(:title, "Edit #{@player.first_name}") %>

<h1> Edit <%= @player.first_name %>'s information</h1>

<%= render partial: "players/form" %>


<%# <% if flash[:errors] %>
<%#   <% flash[:errors].each do |error| %>
<%#     <p><%= e %></p>
<%#   <% end %>
<%# <% end %>
<%#
<%# <%= form_for(@player) do |f| %>
<%#   <p>
<%#       <%= f.label :first_name %>
<%#       <%= f.text_field :first_name %>
<%#   </p>
<%#   <p>
<%#       <%= f.label :last_name %>
<%#       <%= f.text_field :last_name %>
<%#   </p>
<%#   <%= f.submit %>
<%# <% end %>

<!-- <form> action="/players/<%= @player.id%>" method="post" -->
  <!-- Originally HTML didn't allow patch (only GET/POST) => hence RAILS middleware exchanges the VERB from the incoming 'post' to 'patch' -->
<!--   <input type="hidden" name="_method" value="patch"> -->
<!--   <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> -->
<!--   <p> -->
<!--     <label>First name: </label> -->
<!--     <input type="text" name="player[first_name]" value="<%= @player.first_name %>"> -->
<!--   </p> -->
<!--  -->
<!--   <p> -->
<!--     <label>Last name: </label> -->
<!--     <input type="text" name="player[last_name]" value="<%= @player.last_name %>"> -->
<!--   </p> -->
<!--  -->
<!--   <input type="submit" value="Update"> -->
<!-- </form> -->

<!-- <a href="/players">Go back</a> -->
<%= link_to "Home Page", root_path %>

rails_example_app/tdd/app/views/players/index.html.erb
<h1>Listing <%= pluralize(@players.length, "player") %></h1>

<!-- <p>Eduardo Baik</p> -->
<!-- <p>Christopher Burns</p> -->

<table>
  <thead>
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td>
          <%= link_to "Show Profile", player_path(player.id)%> |
          <%= link_to "Edit Profile", edit_player_path(player.id)%> |
          <%= link_to "Delete Profile", player_path(player.id), data: {method: :delete, confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# <%= link_to "New Player", "/players/new" %>
<%# <%= link_to "New Player", players_new_path %>
<%= link_to "New Player", new_player_path %> | <%= link_to "Log Out", "/log_out" %>

rails_example_app/tdd/app/views/players/new.html.erb
<%# <% content_for(:title, "Create Player") %>

<h1> Create a new Player </h1>

<%= render partial: "players/form" %>

<%# <% if flash[:errors] %>
<%#   <% flash[:errors].each do |error| %>
<%#     <p><%= error %></p>
<%#   <% end %>
<%# <% end %>
<%#
<%# <%= form_for(@player) do |f| %>
<%#   <p>
<%#       <%= f.label :first_name %>
<%#       <%= f.text_field :first_name %>
<%#   </p>
<%#   <p>
<%#       <%= f.label :last_name %>
<%#       <%= f.text_field :last_name %>
<%#   </p>
<%#   <%= f.submit %>
<%# <% end %>

rails_example_app/tdd/app/views/players/show.html.erb
<% content_for(:title, "#{@player.first_name}'s Profile") %>

<h1> This is the profile page for <%= @player.first_name %></h1>

<table>
  <thead>
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
    </tr>
  </thead>
  <thead>
    <tr>
      <td><%= @player.first_name%></td>
      <td><%= @player.last_name%></td>
    </tr>
  </thead>
</table>

<!-- <a href="/players">Home Page </a> -->
<%= link_to "Home Page", root_path %>

rails_example_app/tdd/app/views/users/index.html.erb
<!-- <h1>Login and Registration</h1> -->

<% if flash[:errors] %>
  <div class="row">
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  </div>
<% end %>


<div class="row">
  <div id="registration" class="col-md-6">
    <h1>Register</h1>
    <%= form_for @user do |f|%>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>

  <div id="login" class="col-md-6">
    <h1>Login</h1>
    <%= form_tag sessions_path do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= email_field_tag :email %>
      </div>
      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
      <%= submit_tag "Sign in" %>
    <% end %>
  </div>
</div>


<!-- <form> -->
<!--   <div class="form&#45;group"> -->
<!--     <label for="exampleInputEmail1">Email address</label> -->
<!--     <input type="email" class="form&#45;control" id="exampleInputEmail1" placeholder="Email"> -->
<!--   </div> -->
<!--   <div class="form&#45;group"> -->
<!--     <label for="exampleInputPassword1">Password</label> -->
<!--     <input type="password" class="form&#45;control" id="exampleInputPassword1" placeholder="Password"> -->
<!--   </div> -->
<!--   <div class="form&#45;group"> -->
<!--     <label for="exampleInputFile">File input</label> -->
<!--     <input type="file" id="exampleInputFile"> -->
<!--     <p class="help&#45;block">Example block&#45;level help text here.</p> -->
<!--   </div> -->
<!--   <div class="checkbox"> -->
<!--     <label> -->
<!--       <input type="checkbox"> Check me out -->
<!--     </label> -->
<!--   </div> -->
<!--   <button type="submit" class="btn btn&#45;default">Submit</button> -->
<!-- </form> -->